// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYsJPQgZDxlvMdT-HA1QY_YuUwqP8Dm0',
    appId: '1:842844797997:android:2be214fa88fc80f0dd4ca4',
    messagingSenderId: '842844797997',
    projectId: 'ping-chat-4aa80',
    storageBucket: 'ping-chat-4aa80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYsJPQgZDxlvMdT-HA1QY_YuUwqP8Dm0',
    appId: '1:842844797997:android:2be214fa88fc80f0dd4ca4',
    messagingSenderId: '842844797997',
    projectId: 'ping-chat-4aa80',
    storageBucket: 'ping-chat-4aa80.firebasestorage.app',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrYsJPQgZDxlvMdT-HA1QY_YuUwqP8Dm0',
    appId: '1:842844797997:android:2be214fa88fc80f0dd4ca4',
    messagingSenderId: '842844797997',
    projectId: 'ping-chat-4aa80',
    authDomain: 'ping-chat-4aa80.firebaseapp.com',
    storageBucket: 'ping-chat-4aa80.firebasestorage.app',
  );
}
